# Generated by Django 3.2.4 on 2021-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=20)),
                ('salario', models.CharField(max_length=6)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
