# Generated by Django 3.2.4 on 2021-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher'), ('N', 'Não Binário')], max_length=3)),
                ('cpf', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
